// ─────────────────────────────────────────────────────────────────────────────
// BusinessValueOutput — domain entity
//
// Produced by BusinessValueAgent for each PrioritizedFeature.
// Carries the four customer-facing fields requested by the user, plus
// bookkeeping fields for traceability and fallback detection.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Customer-facing business value copy for a single feature, generated (or
 * approximated) by the BusinessValueAgent.
 */
export interface BusinessValueOutput {
  /** Correlation key — matches Feature.id and PrioritizedFeature.feature.id. */
  featureId:   string;
  /** Denormalized feature name for readability in logs and test assertions. */
  featureName: string;

  // ── Four customer-facing fields (as requested by the user) ───────────────

  /**
   * The real-world business pain this feature directly addresses.
   * One sentence, from the customer's perspective.
   * Example: "Operations managers waste hours hunting down energy anomalies across sites."
   */
  businessProblem: string;

  /**
   * The tangible value the customer gains by using this feature.
   * One sentence, outcome-first.
   * Example: "See every device's energy trend in a single view — no manual data pulls."
   */
  businessBenefit: string;

  /**
   * A concrete, observable, or measurable result.
   * Includes a metric estimate where plausible.
   * Example: "Anomalies that took 2 days to surface are now flagged within minutes."
   */
  customerOutcome: string;

  /**
   * Ready-to-use demo narration (≤2 sentences) for the sales engineer to
   * deliver while pointing at this feature on screen.
   * Starts with "With [feature], your team can…"
   */
  salesNarration: string;

  // ── Traceability ─────────────────────────────────────────────────────────

  /**
   * 'llm'      — all four fields were generated by the LLM
   * 'fallback' — LLM call failed; fields were derived from existing Feature metadata
   */
  source: 'llm' | 'fallback';
}

// ─────────────────────────────────────────────────────────────────────────────
// BusinessValueEnrichmentResult — returned by IBusinessValueAgent.enrich()
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Aggregate result from enriching a full set of features.
 * Every input feature has exactly one corresponding output — either LLM-generated
 * or fallback. The arrays are co-indexed with the input PrioritizedFeature array.
 */
export interface BusinessValueEnrichmentResult {
  /** One entry per submitted feature, in the same order as the input array. */
  outputs:        BusinessValueOutput[];
  /** Number of features passed to enrich(). */
  totalSubmitted: number;
  /**
   * Features whose copy was successfully generated by the LLM (source === 'llm').
   * Features using the rule-based fallback are NOT counted here.
   */
  totalEnriched:  number;
  /** ISO timestamp when enrichment completed. */
  enrichedAt:     string;
}
