/**
 * download-broll-videos.ts
 *
 * Downloads 5 royalty-free stock videos from Pexels for the current product.
 * Search queries are generated by Azure OpenAI from APP_PRODUCT_NAME + APP_CONTEXT_TEXT.
 *
 * Network strategy (tried in order):
 *  1. Pexels CDN  — works on open networks / phone hotspot
 *  2. GitHub Release cache (`broll-{APP_SLUG}-latest`) — works on corporate networks
 *     where Pexels CDN is blocked
 *
 * After a successful Pexels download the videos are automatically uploaded to
 * GitHub Releases so future corporate-network runs can pull from there.
 *
 * Usage:
 *   npx ts-node --project tsconfig.scripts.json automation/download-broll-videos.ts
 *
 * Requires: PEXELS_API_KEY, GITHUB_TOKEN, GITHUB_REPO in .env
 */

import * as fs          from 'fs';
import * as path        from 'path';
import * as https       from 'https';
import * as http        from 'http';
import * as dotenv      from 'dotenv';
import { AzureOpenAI } from 'openai';
import { APP_SLUG, OUT_DIR } from './config';

dotenv.config({ path: path.resolve(__dirname, '../.env'), override: true });

// ─── Config ───────────────────────────────────────────────────────────────────

const PEXELS_API_KEY  = process.env['PEXELS_API_KEY']  ?? '';
const PIXABAY_API_KEY = process.env['PIXABAY_API_KEY'] ?? '';
const GITHUB_TOKEN    = process.env['GITHUB_TOKEN']    ?? '';
const GITHUB_REPO     = process.env['GITHUB_REPO']     ?? '';   // "owner/repo"
const RECORDINGS_DIR  = path.join(OUT_DIR, 'recordings');
const PKG_PATH        = path.join(OUT_DIR, 'demo-package.json');
const PRODUCT_NAME    = process.env['APP_PRODUCT_NAME'] ?? 'Enterprise SaaS';
const CONTEXT_TEXT    = process.env['APP_CONTEXT_TEXT'] ?? '';
const BROLL_TAG       = `broll-${APP_SLUG}-latest`;

// ─── GitHub Release helpers ───────────────────────────────────────────────────

interface GHRelease { id: number; tag_name: string; upload_url: string; assets: GHAsset[] }
interface GHAsset   { id: number; name: string; browser_download_url: string; size: number }

function ghFetch(method: string, ghPath: string, body?: object | Buffer, contentType?: string): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const agent = new https.Agent({ rejectUnauthorized: false });
    const isBuffer = Buffer.isBuffer(body);
    const bodyBuf  = isBuffer ? body as Buffer : (body ? Buffer.from(JSON.stringify(body)) : undefined);
    const opts = {
      hostname: 'api.github.com',
      path: ghPath,
      method,
      headers: {
        'User-Agent':    'VideoGenerator/1.0',
        'Authorization': `Bearer ${GITHUB_TOKEN}`,
        'Accept':        'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        ...(bodyBuf ? { 'Content-Type': contentType ?? 'application/json', 'Content-Length': bodyBuf.length } : {}),
      } as Record<string, string | number>,
      agent,
    };
    const req = https.request(opts, res => {
      const chunks: Buffer[] = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => {
        const text = Buffer.concat(chunks).toString();
        try { resolve(text ? JSON.parse(text) : {}); } catch { resolve(text); }
      });
      res.on('error', reject);
    });
    req.setTimeout(60000, () => { req.destroy(new Error('GitHub API timeout')); });
    req.on('error', reject);
    if (bodyBuf) req.write(bodyBuf);
    req.end();
  });
}

/** Upload binary to GitHub release upload URL (different hostname from api.github.com). */
function ghUploadAsset(uploadUrl: string, name: string, filePath: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const buf = fs.readFileSync(filePath);
    const parsed = new URL(uploadUrl.replace(/{.*}$/, '') + `?name=${encodeURIComponent(name)}`);
    const agent = new https.Agent({ rejectUnauthorized: false });
    const req = https.request({
      hostname: parsed.hostname,
      path: parsed.pathname + parsed.search,
      method: 'POST',
      headers: {
        'User-Agent':    'VideoGenerator/1.0',
        'Authorization': `Bearer ${GITHUB_TOKEN}`,
        'Accept':        'application/vnd.github+json',
        'Content-Type':  'application/octet-stream',
        'Content-Length': buf.length,
      },
      agent,
    }, res => {
      res.resume();
      res.on('end', () => resolve());
    });
    req.setTimeout(300000, () => { req.destroy(new Error('Upload timeout')); });
    req.on('error', reject);
    req.write(buf);
    req.end();
  });
}

async function getOrCreateRelease(): Promise<GHRelease | null> {
  if (!GITHUB_TOKEN || !GITHUB_REPO) return null;
  const [owner, repo] = GITHUB_REPO.split('/');
  try {
    const existing = await ghFetch('GET', `/repos/${owner}/${repo}/releases/tags/${BROLL_TAG}`) as GHRelease;
    if (existing?.id) return existing;
  } catch {}
  try {
    const created = await ghFetch('POST', `/repos/${owner}/${repo}/releases`, {
      tag_name: BROLL_TAG,
      name:     `B-roll videos — ${PRODUCT_NAME}`,
      body:     `Auto-cached Pexels stock videos for ${PRODUCT_NAME} demos.`,
      draft:    false,
      prerelease: true,
    }) as GHRelease;
    return created?.id ? created : null;
  } catch { return null; }
}

async function uploadBrollsToGitHub(fileIds: string[]): Promise<void> {
  if (!GITHUB_TOKEN || !GITHUB_REPO) return;
  console.log('\n  Uploading brolls to GitHub Release for future corporate-network use…');
  const [owner, repo] = GITHUB_REPO.split('/');
  let release = await getOrCreateRelease();
  if (!release) { console.warn('  ⚠️  Could not create GitHub release — skipping upload.'); return; }

  // Delete existing assets so we can replace them
  for (const asset of release.assets ?? []) {
    await ghFetch('DELETE', `/repos/${owner}/${repo}/releases/assets/${asset.id}`).catch(() => {});
  }

  for (const id of fileIds) {
    const filePath = path.join(RECORDINGS_DIR, `${id}.mp4`);
    if (!fs.existsSync(filePath)) continue;
    process.stdout.write(`    uploading ${id}.mp4 … `);
    try {
      await ghUploadAsset(release.upload_url, `${id}.mp4`, filePath);
      console.log('done');
    } catch (e) {
      console.log(`failed (${(e as Error).message?.slice(0, 50)})`);
    }
  }
}

async function downloadBrollsFromGitHub(needed: string[]): Promise<string[]> {
  if (!GITHUB_TOKEN || !GITHUB_REPO) return [];
  const [owner, repo] = GITHUB_REPO.split('/');
  let release: GHRelease | null = null;
  try {
    release = await ghFetch('GET', `/repos/${owner}/${repo}/releases/tags/${BROLL_TAG}`) as GHRelease;
  } catch {}
  if (!release?.assets?.length) return [];

  console.log(`  GitHub Release found (${release.assets.length} asset(s)) — downloading cached brolls…`);
  const downloaded: string[] = [];
  for (const id of needed) {
    const asset = release.assets.find(a => a.name === `${id}.mp4`);
    if (!asset || asset.size < 100_000) continue;
    const destFile = path.join(RECORDINGS_DIR, `${id}.mp4`);
    process.stdout.write(`    [${id}] from GitHub … `);
    try {
      await downloadViaHttps(asset.browser_download_url, destFile);
      const size = fs.statSync(destFile).size;
      console.log(`done (${fmt(size)})`);
      downloaded.push(id);
    } catch (e) {
      console.log(`failed (${(e as Error).message?.slice(0, 50)})`);
    }
  }
  return downloaded;
}

// ─── Pexels / Pixabay helpers ─────────────────────────────────────────────────

interface PexelsVideoFile { link: string; width: number; height: number; quality: string }
interface PexelsVideo     { id: number; video_files: PexelsVideoFile[] }
interface PexelsSearchResponse { videos: PexelsVideo[] }
interface PixabayVideoHit { videos: { large?: { url: string }; medium?: { url: string } } }
interface PixabayVideoResponse { hits: PixabayVideoHit[] }

function fetchJson(url: string, headers: Record<string, string> = {}, timeoutMs = 30000): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const agent = new https.Agent({ rejectUnauthorized: false });
    const parsed = new URL(url);
    const options = {
      hostname: parsed.hostname,
      path:     parsed.pathname + parsed.search,
      headers:  { 'User-Agent': 'VideoGenerator/1.0', ...headers },
      agent,
    };
    function get(opts: typeof options): void {
      const req = https.get(opts, res => {
        if (res.statusCode && res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          const r = new URL(res.headers.location, `https://${opts.hostname}`);
          return get({ ...options, hostname: r.hostname, path: r.pathname + r.search });
        }
        let data = '';
        res.on('data', (c: Buffer) => { data += c.toString(); });
        res.on('end', () => { try { resolve(JSON.parse(data)); } catch (e) { reject(e); } });
        res.on('error', reject);
      });
      req.setTimeout(timeoutMs, () => { req.destroy(new Error('Timeout')); });
      req.on('error', reject);
    }
    get(options);
  });
}

/** Download a binary file via Node.js HTTPS/HTTP (options-object form, follows redirects). */
function downloadViaHttps(url: string, destPath: string, timeoutMs = 120000): Promise<void> {
  return new Promise((resolve, reject) => {
    fs.mkdirSync(path.dirname(destPath), { recursive: true });
    const httpsAgent = new https.Agent({ rejectUnauthorized: false });

    function get(currentUrl: string): void {
      const parsed  = new URL(currentUrl);
      const isHttps = currentUrl.startsWith('https');
      const commonHeaders: Record<string, string> = { 'User-Agent': 'VideoGenerator/1.0' };
      if (isHttps && parsed.hostname.includes('github')) {
        commonHeaders['Authorization'] = `Bearer ${GITHUB_TOKEN}`;
      }

      const reqCallback = (res: http.IncomingMessage) => {
        const status = res.statusCode ?? 0;
        if (status >= 300 && status < 400 && res.headers.location) {
          res.resume();
          const loc = res.headers.location;
          return get(loc.startsWith('http') ? loc : `${isHttps ? 'https' : 'http'}://${parsed.hostname}${loc}`);
        }
        if (status !== 200) { res.resume(); return reject(new Error(`HTTP ${status}`)); }
        const file = fs.createWriteStream(destPath);
        res.pipe(file);
        file.on('finish', () => file.close(() => resolve()));
        file.on('error', err => { try { fs.unlinkSync(destPath); } catch {} reject(err); });
        res.on('error',  err => { try { fs.unlinkSync(destPath); } catch {} reject(err); });
      };

      let req: http.ClientRequest;
      if (isHttps) {
        req = https.get({
          hostname: parsed.hostname,
          port:     parsed.port ? parseInt(parsed.port, 10) : 443,
          path:     parsed.pathname + parsed.search,
          headers:  commonHeaders,
          agent:    httpsAgent,
        }, reqCallback);
      } else {
        req = http.get({
          hostname: parsed.hostname,
          port:     parsed.port ? parseInt(parsed.port, 10) : 80,
          path:     parsed.pathname + parsed.search,
          headers:  commonHeaders,
        }, reqCallback);
      }
      req.setTimeout(timeoutMs, () => { req.destroy(new Error('Download timeout')); });
      req.on('error', reject);
    }
    get(url);
  });
}

async function pexelsSearch(query: string, usedIds: Set<number> = new Set()): Promise<PexelsVideo | null> {
  const url = `https://api.pexels.com/videos/search?query=${encodeURIComponent(query)}&per_page=5&orientation=landscape&size=medium`;
  try {
    const data   = await fetchJson(url, { Authorization: PEXELS_API_KEY }) as PexelsSearchResponse;
    const videos = data.videos ?? [];
    // Different queries can share a top result (limited stock footage for a niche
    // topic) — prefer a result not already used by an earlier b-roll scene so two
    // scenes don't end up showing the identical clip.
    return videos.find(v => !usedIds.has(v.id)) ?? videos[0] ?? null;
  } catch { return null; }
}

async function pixabaySearch(query: string, usedUrls: Set<string> = new Set()): Promise<string | null> {
  if (!PIXABAY_API_KEY) return null;
  const url = `https://pixabay.com/api/videos/?key=${PIXABAY_API_KEY}&q=${encodeURIComponent(query)}&per_page=5&video_type=film`;
  try {
    const data = await fetchJson(url) as PixabayVideoResponse;
    const hits = data.hits ?? [];
    const urlOf = (h: PixabayVideoResponse['hits'][number]) => h.videos.large?.url ?? h.videos.medium?.url ?? null;
    for (const hit of hits) {
      const u = urlOf(hit);
      if (u && !usedUrls.has(u)) return u;
    }
    return hits[0] ? urlOf(hits[0]) : null;
  } catch { return null; }
}

function pickBestFile(files: PexelsVideoFile[]): PexelsVideoFile | null {
  const hd = files.find(f => f.quality === 'hd' && f.width >= 1280);
  return hd ?? files.find(f => f.width >= 854) ?? files[0] ?? null;
}

function fmt(bytes: number): string {
  return bytes > 1_000_000 ? `${(bytes / 1_000_000).toFixed(1)} MB` : `${(bytes / 1024).toFixed(0)} KB`;
}

// ─── AI query generation ──────────────────────────────────────────────────────

async function generateBrollQueries(brollSubtitles: string[] = []): Promise<string[]> {
  const customTerms = (process.env['BROLL_SEARCH_TERMS'] ?? '').split(',').map(t => t.trim()).filter(Boolean);
  if (customTerms.length >= 3) return customTerms.slice(0, 5);

  const apiKey     = process.env['AZURE_OPENAI_API_KEY']    ?? '';
  const endpoint   = process.env['AZURE_OPENAI_ENDPOINT']   ?? '';
  const deployment = process.env['AZURE_OPENAI_DEPLOYMENT'] ?? '';

  if (!apiKey || !endpoint || !deployment) return genericFallbackQueries();

  const subtitleBlock = brollSubtitles.length > 0
    ? `\n\nThe video's opening B-roll scenes will show these exact problem statements:\n${brollSubtitles.map((s, i) => `  Scene ${i + 1}: "${s}"`).join('\n')}\nEach query must match the corresponding scene's problem visually.`
    : '';

  const prompt = `You are helping select stock video footage for a professional B2B SaaS demo video.

Product: ${PRODUCT_NAME}
Context: ${CONTEXT_TEXT.slice(0, 800)}${subtitleBlock}

Generate exactly ${Math.max(brollSubtitles.length, 3)} short Pexels video search queries (2-5 words each).
Each query must:
- Visually represent the problem statement for that scene
- Show real-world situations: people struggling with manual work, disconnected systems, or operational chaos specific to this product's domain
- Be concrete enough to return real stock footage (no abstract or metaphorical terms)
- Be specific to this product's industry (not generic "business people")

Return ONLY a JSON array of strings. Example: ["query one", "query two", "query three"]`;

  try {
    const client = new AzureOpenAI({ apiKey, endpoint, deployment, apiVersion: process.env['OPENAI_API_VERSION'] ?? '2024-12-01-preview' });
    const resp   = await client.chat.completions.create({
      model: deployment, messages: [{ role: 'user', content: prompt }],
      max_completion_tokens: 1200, reasoning_effort: 'low',
    });
    const text   = resp.choices[0]?.message?.content?.trim() ?? '';
    const match  = text.match(/\[[\s\S]*\]/);
    if (match) {
      const queries: string[] = JSON.parse(match[0]);
      if (Array.isArray(queries) && queries.length >= Math.max(brollSubtitles.length, 3)) {
        console.log('  AI-generated search queries (matched to B-roll scenes):');
        queries.forEach((q, i) => console.log(`    broll-${i}: "${q}"`));
        return queries;
      }
    }
  } catch (e) {
    console.warn(`  ⚠️  AI query generation failed (${(e as Error).message?.slice(0, 60)}) — using generic queries.`);
  }

  return genericFallbackQueries();
}

function genericFallbackQueries(): string[] {
  return [
    'professional team office technology',
    'business operations dashboard analytics',
    'team collaboration meeting technology',
    'industry workers monitoring equipment',
    'digital transformation enterprise office',
  ];
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log('\n═══════════════════════════════════════════════════════════════');
  console.log(`  📹  B-Roll Downloader — ${PRODUCT_NAME}`);
  console.log('═══════════════════════════════════════════════════════════════\n');

  if (!PEXELS_API_KEY) {
    console.error('  ❌  PEXELS_API_KEY not set in .env\n');
    process.exit(1);
  }

  fs.mkdirSync(RECORDINGS_DIR, { recursive: true });

  if (!fs.existsSync(PKG_PATH)) {
    console.error('  ❌  demo-package.json not found — run the recording pipeline first.\n');
    process.exit(1);
  }

  const pkg = JSON.parse(fs.readFileSync(PKG_PATH, 'utf-8'));
  const brollScenes: { id: string; subtitle?: string; videoPath?: string; [k: string]: unknown }[] = pkg.brollScenes ?? [];
  // Use actual broll count from demo-package.json (enterprise may have 3, others 5)
  const brollCount = Math.max(brollScenes.length, 3);
  const brollIds   = Array.from({ length: brollCount }, (_, i) => `broll-${i}`);

  // ── Step 1: Try Pexels ──────────────────────────────────────────────────────
  // Pass broll subtitles so AI can generate queries that match the actual problem statements
  const brollSubtitles = brollScenes.map(s => s.subtitle ?? '').filter(Boolean);
  const queries = await generateBrollQueries(brollSubtitles);
  const succeeded: string[] = [];
  const usedPexelsIds = new Set<number>();
  const usedPixabayUrls = new Set<string>();

  console.log('\n  Trying Pexels…');
  for (let i = 0; i < brollIds.length; i++) {
    const id       = brollIds[i];
    const query    = queries[i] ?? genericFallbackQueries()[i];
    const destFile = path.join(RECORDINGS_DIR, `${id}.mp4`);
    const relPath  = `recordings/${id}.mp4`;

    process.stdout.write(`  [${id}]  "${query}" … `);

    let ok = false;

    const pexelsVideo = await pexelsSearch(query, usedPexelsIds);
    if (pexelsVideo) {
      const pexelsFile = pickBestFile(pexelsVideo.video_files);
      if (pexelsFile) {
        process.stdout.write(`Pexels #${pexelsVideo.id} → `);
        try {
          await downloadViaHttps(pexelsFile.link, destFile);
          const size = fs.statSync(destFile).size;
          if (size < 100_000) throw new Error(`too small`);
          console.log(`✓ ${fmt(size)}`);
          ok = true;
          usedPexelsIds.add(pexelsVideo.id);
        } catch (e) {
          process.stdout.write(`CDN blocked → `);
        }
      }
    }

    if (!ok) {
      const pixUrl = PIXABAY_API_KEY ? await pixabaySearch(query, usedPixabayUrls) : null;
      if (pixUrl) {
        try {
          await downloadViaHttps(pixUrl, destFile);
          const size = fs.statSync(destFile).size;
          if (size < 100_000) throw new Error('too small');
          console.log(`✓ Pixabay ${fmt(size)}`);
          ok = true;
          usedPixabayUrls.add(pixUrl);
        } catch {}
      }
      if (!ok) console.log('not available on this network');
    }

    if (ok) {
      succeeded.push(id);
      const scene = brollScenes.find(s => s.id === id);
      if (scene) scene.videoPath = relPath;
    }
  }

  // ── Step 2: Upload successful downloads to GitHub (cache for corp network) ──
  if (succeeded.length > 0 && GITHUB_TOKEN && GITHUB_REPO) {
    await uploadBrollsToGitHub(succeeded);
  }

  // ── Step 3: Fall back to GitHub Release for anything still missing ──────────
  const missing = brollIds.filter(id => !succeeded.includes(id));
  if (missing.length > 0 && GITHUB_TOKEN && GITHUB_REPO) {
    console.log(`\n  ${missing.length} file(s) not downloaded from Pexels — trying GitHub Release cache…`);
    const fromGH = await downloadBrollsFromGitHub(missing);
    for (const id of fromGH) {
      const scene = brollScenes.find(s => s.id === id);
      if (scene) scene.videoPath = `recordings/${id}.mp4`;
      succeeded.push(id);
    }
  }

  // ── Write results ────────────────────────────────────────────────────────────
  if (succeeded.length > 0) {
    fs.writeFileSync(PKG_PATH, JSON.stringify(pkg, null, 2));
    console.log(`\n  ✅  ${succeeded.length}/5 broll video(s) ready`);
    console.log(`  📦  demo-package.json updated\n`);
  } else {
    console.log('\n  ⚠️   No broll videos available.');
    console.log('      On a network where Pexels CDN is blocked:');
    console.log('      → Connect to phone hotspot, run npm run broll:download once');
    console.log('      → Videos upload to GitHub and work on corporate network automatically.\n');
    process.exit(1);
  }

  console.log('═══════════════════════════════════════════════════════════════\n');
}

main().catch(err => { console.error(err); process.exit(1); });
